MDS_Tour/Controllers/DefaultController.cs
using BusinessLayer.Abstract;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace MDS_Tour.Controllers
{
    [AllowAnonymous]
    public class DefaultController : Controller
    {
        IDestinationService _destinationService;

        public DefaultController(IDestinationService destinationService)
        {
            _destinationService = destinationService;
        }

        public IActionResult Index()
        {
            List<Destination> destinationList = new List<Destination>(_destinationService.TGetList());
            //List<string> strings = new List<string>() { "Ozan","Mucize"};
            return View(destinationList);
        }

        //[HttpGet]
        //public IActionResult Detay(int id)
        //{
        //    List<Destination> destinationList = new List<Destination>(_destinationService.TGetList());
        //    //List<string> strings = new List<string>() { "Ozan","Mucize"};
        //    return View(destinationList);
        //}
        //[HttpPost]
        //public IActionResult Detay(Destination destination)
        //{
        //    return RedirectPermanent("/Destination/DestinationDetails/");
        //}


        
    }
}

MDS_Tour/Controllers/DestinationController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace MDS_Tour.Controllers
{
    [AllowAnonymous]
    public class DestinationController : Controller
    {
        DestinationManager destinationManager = new DestinationManager(new EfDestinationDal());  //DestinationManager sınıfından bir nesne türettik paramaetre belediği içinde EfDestinationDal ı ekledil
        private readonly UserManager<AppUser> _userManager;

        public DestinationController(UserManager<AppUser> userManager)
        {
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var data = destinationManager.TGetList();
            return View(data);
        }

        [HttpGet]
        public async Task<IActionResult> DestinationDetails(int id)
        {
            if (!string.IsNullOrEmpty(User.Identity.Name))
            {
                var data2 = await _userManager.FindByNameAsync(User.Identity.Name);  //Kullanıcı adına göre bul bulduktan sonra bu bulduğun id yi ViewBag.userID ye yapıştır
                ViewBag.userId = data2.Id;
            }
            var data = destinationManager.TGetDestinationWithGuideList(id);
            return View(data);
        }
        
        [HttpPost]
        public IActionResult DestinationDetails(Destination p)
        {
            return View();
        }
    }
}

MDS_Tour/Views/Shared/Components/SliderPartial/Default.cshtml
@*@model List<EntityLayer.Concrete.Destination>*@
@model List<Destination>


<section class="w3l-main-slider" id="home">
    <div class="banner-content">
        <div id="demo-1"
             data-zs-src='["/Traversal-Content/Traversal-Liberty/assets/images/bodrum1.jpg", "/Traversal-Content/Traversal-Liberty/assets/images/slider1.jpg","/Traversal-Content/Traversal-Liberty/assets/images/antalya1.jpg", "/Traversal-Content/Traversal-Liberty/assets/images/barcelona.jpg"]'
             data-zs-overlay="dots">
            <div class="demo-inner-content">
                <div class="container">
                    <div class="banner-infhny">
                        <h3>You don't need to go far to find what matters.</h3>
                        <h6 class="mb-3">Discover your next adventure</h6>
                        <div class="flex-wrap search-wthree-field mt-md-5 mt-4">

                            <form asp-action="DestinationDetails" asp-controller="Destination" method="get" class="booking-form">
                                <div class="row book-form">
                                    <div class="form-input col-md-4 mt-md-0 mt-3">

                                        <select name="id">
                                            @foreach (var item in Model)
                                            {
                                                <option value="@item.DestinationId">@item.City</option>

                                            }
                                        </select>
                                    </div>
                                    <div class="bottom-btn col-md-4 mt-md-0 mt-3">
                                      
                                        <button class="btn btn-style btn-secondary" type="submit">Search</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>